### ISSUE TITLE
Remove default localhost:6379 server

### ISSUE THREAD

**Issue by IanKemp** [ekvedaras/redis-gui#25]
Not everyone has Redis running locally, and those who don't get arbitrary errors in the UI when they start the app.

A better workflow would be to display the "Add server" dialog if no servers are in the app's server list when it starts.

**Comment by madhukumaar** [comment]
Agreed, was annoyed when I started receiving errors when the app was started

**Comment by ekvedaras** [comment]
Addressed in `v2`
