### ISSUE TITLE
Edit servers list is broken. Can't edit.

### ISSUE THREAD

**Issue by jmwielandt** [ekvedaras/redis-gui#27]
![imagen](https://user-images.githubusercontent.com/37153467/144878755-403e8436-3763-47a4-a3ac-76e868a01816.png)

I can't edit the second one.

**Comment by kice** [comment]
1. If there no server on the list, you cannot open the server edit dialog
2. way too many popup if connection to server is failed. it is okay that retry too many time, but not necessary 
3. suggesting to add a shortcut menu to open the configuration file folder

**Comment by ekvedaras** [comment]
@kice thanks for your input 👍 What do you mean by configuration folder? 🤔 Servers list modal? Settings modal or something else?

**Comment by ekvedaras** [comment]
> 1. If there no server on the list, you cannot open the server edit dialog
> 2. way too many popup if connection to server is failed. it is okay that retry too many time, but not necessary
> 3. suggesting to add a shortcut menu to open the configuration file folder

Will be taken into account in v2
