### ISSUE TITLE
ssh setting parse private key fail

### ISSUE THREAD

**Issue by Kfanup** [ekvedaras/redis-gui#3]
hint: 
Error Cannot parse private key: Unsupported  key format

**Comment by Kfanup** [comment]
used default private key path

**Comment by Kfanup** [comment]
used default private key path

**Comment by Kfanup** [comment]
transfer openssh key to rsa key can help this, sorry

**Comment by ekvedaras** [comment]
Hey, I'll check the underlying libraries, maybe there are some updates for this 🙂
