### ISSUE TITLE
 Key names

### ISSUE THREAD

**Issue by Rammaukinn** [ekvedaras/redis-gui#32]
Hi, I don’t understand why the first underscore is not displayed. For example, the key is called incoming_call_1205, then it is displayed on the panel as incomingcall_1205, I will attach a screen for clarity. Thanks in advance!
![image](https://user-images.githubusercontent.com/47497480/148585134-4c6f714b-7fbd-404b-94e9-7c714664a465.png)

**Comment by ekvedaras** [comment]
Interesting 🤔 There is some magic happening to make grouping to folders, but that shouldn't interfere with 1st underscore 🤷 Will take a look at this.

**Comment by Lopinfal** [comment]
> Interesting 🤔 There is some magic happening to make grouping to folders, but that shouldn't interfere with 1st underscore 🤷 Will take a look at this.

I will wait for the solution of the bug

**Comment by ekvedaras** [comment]
Fixed in `v1.2.10`

**Comment by soulwawa** [comment]
hi 🙋‍♂️ @ekvedaras 

**perfect v1.2.12**
<img width="186" alt="스크린샷 2023-01-12 오후 2 15 44" src="https://user-images.githubusercontent.com/14883810/211983355-6426ea1e-5000-4382-9c76-721a35c41c84.png">


**but, v2.2.0 first underscore is not displayed**
<img width="179" alt="스크린샷 2023-01-12 오후 2 15 48" src="https://user-images.githubusercontent.com/14883810/211983426-36d2ce6e-9286-4e96-9cb9-0eb7046f0eaf.png">
