### ISSUE TITLE
Key names - again

### ISSUE THREAD

**Issue by eruanno123** [ekvedaras/redis-gui#34]
Related to #32.

I wonder if there could be an option in the setting panel that would restore the original behaviour from v1.2.9.

In my application I have an extra abstraction layer I called "virtual key". For example
- `foo.bar.baz` - translated to hash `foo.bar` and field `baz`.
- `foo.group:1.baz` - translated to hash `foo.group:1` and field `baz`.
- `foo.group:2.baz` - translated to hash `foo.group:2` and field `baz`.
- `foo.bar.@baz` - translated to string `foo.bar.@baz`. I am using `@` symbol to distinguish what Redis command should be used (SET/GET vs HSET/HGET).

In the Redis GUI I am using `.` as a namespace separator.

In _v1.2.9_ I was perfectly fine with the tree view like this:

![image](https://user-images.githubusercontent.com/3846502/149523015-09306bb2-720f-4d4f-ace8-a3bdb1fe2062.png)

Even if there was a duplicated `bar`, the icon on the left did let me distinguish the strings from hashes.

Now, in _v1.2.10_ I am getting this, which IMO is quite confusing:

![image](https://user-images.githubusercontent.com/3846502/149522226-c674202c-bdac-47f5-bba7-29d472c7fd18.png)

**Comment by ekvedaras** [comment]
Hey. That's an interesting one 🙂 Either way, you should not see that `_+_+_` at all. Yeah, it is probably colliding with having the same folder name and key at the same level. Will take a look at this 👍

**Comment by eruanno123** [comment]
Thanks for the quick response!

**Comment by ekvedaras** [comment]
Fixed in `v1.2.11`
