### ISSUE TITLE
NOPERM this user has no permissions to run the 'info' command or its subcommand

### ISSUE THREAD

**Issue by Ajju2211** [ekvedaras/redis-gui#37]
### NOPERM this user has no permissions to run the 'info' command or its subcommand (Red Alert in GUI)
I am getting this alert because the user ACL is Read only permission .I found the solution to this issue over [here](https://github.com/luin/ioredis/issues/1211#issuecomment-790977399),
it says to disable the info call with

>  enableReadyCheck: false

 on RedisOptions. But their is no RedisOptions to pass through this GUI so please provide such option.

**_Error Screenshot_**
![image](https://user-images.githubusercontent.com/43109538/151224265-7b592463-915d-4cdd-a94b-e85aa8d0a047.png)

**Comment by ekvedaras** [comment]
Interesting. I'll see if the parts that call INFO could be disabled

**Comment by ekvedaras** [comment]
Should be addressed in `v1.2.12`. Let me know if it is still an issue.
