### ISSUE TITLE
No infobox

### ISSUE THREAD

**Issue by flobuc** [ekvedaras/redis-gui#52]
Version 2.0 Windows

Infobox would be nice to check the version number

**Comment by flobuc** [comment]
This is an enhancement, but I cannot change the label. Sorry.

**Comment by ekvedaras** [comment]
You should be able to see it in About section
<img width="396" alt="image" src="https://user-images.githubusercontent.com/3586184/164682823-08e7a26a-8eab-46e5-9ca5-0f4857a1a97b.png">

But I agree it would be nice to see the version somewhere at the bottom maybe.

**Comment by flobuc** [comment]
Sorry, but I can't find the About section?

**Comment by ekvedaras** [comment]
Well on mac os it's under `redis-gui` (first) menu item. I don't remember how it is on windows. Might be under `File`. Maybe it was under `Help` on Windows which gets replaced with custom items 🤔 Need to find windows laptop somewhere to test then.. 😄
