### ISSUE TITLE
ssh tunnel using private key

### ISSUE THREAD

**Issue by mstdoc** [ekvedaras/redis-gui#61]
Hi, i'm trying to connect to redis db using ssh tunnel with private key auth.
But getting error "Cannot parse privateKey: Encrypted OpenSSH private key detected, but no passphrase given"

How can i enter private key passphrase?

Additionally - error reproduces even with empty field for private key path

Maybe i'm doing it the wrong way?

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/60098801/181597823-d3845fd7-e0aa-4c17-baa7-08e31707532c.png)
![Untitled 2](https://user-images.githubusercontent.com/60098801/181597826-0d4bd1bb-61c9-434c-b8eb-1fe223c3efa4.png)

**Comment by ekvedaras** [comment]
Right, need a field for password. Or ask it every time 🤷

**Comment by mstdoc** [comment]
Is there a way to enter passphrase in any config file for a "quick fix"?

**Comment by ekvedaras** [comment]
Not at the moment. If you control the server, you could make a passwordless key and trust it temporarily if you like being adventurous :)
