### ISSUE TITLE
Work with redis db that have password?

### ISSUE THREAD

**Issue by patchthecode** [ekvedaras/redis-gui#62]
Some redis DB has password for security.
Any chance to update this app to support this?

**Comment by ekvedaras** [comment]
You can already do that

**Comment by patchthecode** [comment]
..how do i do it?

**Comment by ekvedaras** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/3586184/189056838-e19d5746-1c26-4600-b883-f8c86d2d5d3d.png">
Password can be set at the bottom right.
