### ISSUE TITLE
Windows 11 window buttons broken

### ISSUE THREAD

**Issue by marcobaldo** [ekvedaras/redis-gui#65]
On a fresh install of Windows 11, in addition to the missing application icon at the top left, the window buttons are broken.

In the screenshot below, you can see that the button icons themselves aren't aligned by the hitbox. Clicking on minimize or close don't appear to do anything. Clicking on the restore (middle) button "freezes" the app, as if there is an invisible dialog that makes everything unclickable, but doesn't actually cause the app to go into Not Responding.

![image](https://user-images.githubusercontent.com/1984893/202709477-bb2c29e4-0f04-4ab8-9e9d-3c0711249f96.png)

**Comment by Karman40** [comment]
for me also

**Comment by ekvedaras** [comment]
I've seen this, but not sure how to solve it. `custom-electron-titlebar` package is used for this. Works fine on OSX and I don't have easy means of testing it on windows. Even when I did once I don't get why it crashes and looks broken in the first place. Any help would be appreciated.

**Comment by luca0898** [comment]
any news on this topic? I'm having this problem too

**Comment by ekvedaras** [comment]
Not yet, and won't be able to for a couple of weeks. And then I need to find a windows laptop 🤷

**Comment by AliKhadivi** [comment]
also for me in windows 11 and ubuntu desktop 22.04

**Comment by AliKhadivi** [comment]
I found a good alternative:  https://github.com/qishibo/AnotherRedisDesktopManager

**Comment by tankorsmash** [comment]
This is also happening on Windows 10.
