### ISSUE TITLE
JSON Values Not Rendered When RedisJSON Module Installed

### ISSUE THREAD

**Issue by the-wondersmith** [ekvedaras/redis-gui#71]
**Describe the bug**

`redis-gui` does not handle JSON values when their type is reported by the cluster to be `ReJSON-RL (raw)`. The type _is_ accurately displayed in the UI, hovering over it _does_ properly switch the mouse cursor to the `？` icon, and clicking it _does_ still display the [Redis Data Types](https://redis.io/docs/data-types/) documentation, but the UI never actually loads the selected key's value - it displays the `Loading ↻` animation ad infinitum.

This behavior only seems to happen when the connected cluster has the [RedisJSON](https://github.com/RedisJSON/RedisJSON) module installed / loaded.

**To Reproduce**

1. Enable the [RedisJSON](https://github.com/RedisJSON/RedisJSON) module
2. Set some JSON-valued key: `redis-cli -h {REDIS HOST} -p 6379 JSON.SET some-json-key '$' '{"some":{"json":"value"}}'`
3. Attempt to load the `some-json-key` value in `redis-gui`

**Expected behavior**
The UI should load the values as JSON values.

**Comment by jtoronto** [comment]
Having the same issue.

**Comment by ekvedaras** [comment]
RedisJSON module support added in `v2.3.0`

**Comment by the-wondersmith** [comment]
@ekvedaras You're incredible. Thank you!
